-- MySQL Script generated by MySQL Workbench
-- Tue Sep 21 18:04:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `IDPlayer` INT NOT NULL AUTO_INCREMENT,
  `Nick` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IDPlayer`),
  UNIQUE INDEX `Nick_UNIQUE` (`Nick` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lobby` (
  `IDLobby` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Winner` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDLobby`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlayersInLobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlayersInLobby` (
  `IDPlayersInLobby` INT NOT NULL AUTO_INCREMENT,
  `IDLobby` INT NOT NULL,
  `IDPlayer` INT NOT NULL,
  `SpendTime` TIME NULL,
  `Round` INT NULL,
  `Money` INT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`IDPlayersInLobby`, `IDLobby`, `IDPlayer`),
  INDEX `fk_PlayersInLobby_Lobby_idx` (`IDLobby` ASC) VISIBLE,
  INDEX `fk_PlayersInLobby_Player_idx` (`IDPlayer` ASC) INVISIBLE,
  CONSTRAINT `fk_PlayersInLobby_Lobby`
    FOREIGN KEY (`IDLobby`)
    REFERENCES `mydb`.`Lobby` (`IDLobby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayersInLobby_Player`
    FOREIGN KEY (`IDPlayer`)
    REFERENCES `mydb`.`Player` (`IDPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
